# Generated by Django 4.0.5 on 2022-06-12 09:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('owner', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=120)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('expected_delivery_date', models.DateField(default=datetime.datetime(2022, 6, 17, 15, 7, 37, 174061), null=True)),
                ('status', models.CharField(choices=[('order_placed', 'order_placed'), ('dispatched', 'dispatched'), ('in_transit', 'in_transit'), ('delivered', 'delivered'), ('order_cancelled', 'order_cancelled')], default='order_placed', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
